version: "3.9"

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: conduitdb
      POSTGRES_USER: conduit
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432        
    networks:
      - conduit_db
    restart: unless-stopped

networks:
  conduit_db:
    driver: bridge